service: futurelogix-backend

#frameworkVersion: "3" # Ensure you have Serverless Framework v3 or later

provider:
  name: aws
  runtime: nodejs20.x # Or a later compatible version
  stage: dev # You can have 'dev', 'prod', etc.
  region: eu-west-2 # Or your desired AWS region (e.g., us-east-1)
  # Ensure Lambda can access RDS within your VPC
  vpc:
    securityGroupIds:
      - sg-0e8dfc01a7a63952f # rds-lambda-1
      - sg-092b57e643c8aea7f # futurelogix-sg
      - sg-0f688fba8f11ddc61 # lambda-rds-1
      #- sg-056255b5b10f4ad9d # lambda-rds-2
      #- sg-0c6e1b7f3efcc31e3 # lambda-rds-3
      #- sg-033a6ff5b3b53c1dc # lambda-rds-4
      #- sg-0df3e50722c22f10a # lambda-rds-5
      #- sg-096f5be10f343c7ac # lambda-rds-6
      #- sg-0bb17b13c11359fe6 # lambda-rds-7
    subnetIds:
      - subnet-0e49ffbd10a18b237
      - subnet-0ae08e9da3278f59c
      - subnet-00463b83c6c02b2a3
  environment:
    DB_HOST: ${env:DB_HOST}
    DB_USER: ${env:DB_USER}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_DATABASE: ${env:DB_DATABASE}
    DB_PORT: ${env:DB_PORT}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "ses:SendEmail" # If you want to send emails (e.g., for contact form)
          Resource: "*"

functions:
  # Your function definitions go here. For example:
  getBlogPosts:
    handler: handler.getBlogPosts
    events:
      - http:
          path: blog
          method: get
          cors: true

  getBlogPost:
    handler: handler.getBlogPost
    events:
      - http:
          path: blog/{slug}
          method: get
          cors: true

  submitFeedback:
    handler: handler.submitFeedback
    events:
      - http:
          path: feedback
          method: post
          cors: true

  submitConsultation:
    handler: handler.submitConsultation
    events:
      - http:
          path: consultation
          method: post
          cors: true

  getFeedback:
    handler: handler.getFeedback
    events:
      - http:
          path: feedback/all # Or just 'feedback' if you want to reuse the path, but be careful with methods
          method: get
          cors: true
          private: true # Recommended for admin endpoints
