# backend/serverless.yml
service: futurelogix-backend

frameworkVersion: "3"

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-plugin-include-dependencies

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  timeout: 30
  memorySize: 512
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    JWT_SECRET: ${env:JWT_SECRET}
    NODE_ENV: production
  vpc:
    securityGroupIds:
      - sg-0e501d3f1f478caff # IMPORTANT: REPLACE with your Lambda security group ID (will be created on first deploy, then update)
    subnetIds:
      - subnet-0a83d9a1b4d7d02d7
      - subnet-06b4946db48272446
      - subnet-0398b442ad7d22a53
      - subnet-01d47e8a559b1d91b
      - subnet-029d4c56684c1e221
      - subnet-057b10771dcb46f06
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ec2:CreateNetworkInterface
            - ec2:DescribeNetworkInterfaces
            - ec2:DeleteNetworkInterface
          Resource: "*"
        - Effect: Allow
          Action:
            - rds-db:connect
          Resource: "arn:aws:rds:us-east-1:257394451798:db:futurelogix-db/*"

functions:
  api:
    handler: server.handler
    events:
      - http:
          path: /
          method: any
          cors: true
      - http:
          path: /{proxy+}
          method: any
          cors: true

custom:
  serverless-offline:
    httpPort: 5000
    lambdaPort: 5001
  dotenv:
    path: ./.env
